# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches : [ master ]
  pull_request : 
    branches : [ master ]
      
    

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root1234
          MYSQL_DATABASE: smsdb
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      run: |
          mysql --host 127.0.0.1 --port 33306 -uroot -proot1234 -e "SHOW DATABASES LIKE 'smsdb';" 2>/dev/null



    steps:

    - uses: actions/checkout@v3
    - name: Set up JDK 19.0.1
      uses: actions/setup-java@v3
      with:
        java-version: '19.0.1'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
      

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}


