# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches : [ master ]
  pull_request : 
    branches : [ master ]

    

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write



    steps:

    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306 
        container port: 3306
        character set server: 'utf8' 
        collation server: 'utf8_general_ci' 
        mysql version: '8.0' 
        mysql database: 'smsdb' 
        mysql root password: root1234 
        mysql user: 'developer' 
        mysql password: 1234 

    - uses: actions/checkout@v3
    - name: Set up JDK 19.0.1
      uses: actions/setup-java@v3
      with:
        java-version: '19.0.1'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        


    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    
    - uses: actions/checkout@v2
    - name: doker login
      env:
        Docker_Username: ${{secrets.DOCKER_USERNAME}}
        Docker_Password: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $Docker_Username -p $Docker_Password-stdin
        
   


